version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.15.2
    hostname: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      - logging

  node-exporter:
    image: prom/node-exporter:v0.18.1
    ports:
      - 9100:9100
    networks:
      - logging

  grafana:
    image: grafana/grafana:6.5.2
    hostname: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - logging

networks:
  logging:
    driver: bridge
    # To enable IPv6 uncomment below lines
#    driver_opts:
#        com.docker.network.enable_ipv6: "true"
